### ISSUE TITLE
modDesc descVersion 23 not 21

### ISSUE THREAD

**Issue by sootysax** [Mogli12/AutoTractor#1]
So I tried installing both AutoTractor and AutoCombine dev versions..  had no luck getting them to be recognized by FS15.   Then noticed that the modDesc Version had been changed from Version 21 to 23.   I changed both back to 21, and am able to load them into FS15

**Comment by Mogli12** [comment]
Hi, Do you use FS15 patch 1.3? I think version 23 should be for FS15 patch 1.3 or higher. Giants changed some functions of the build-in hired workers.

**Comment by sootysax** [comment]
yes, 1.3 beta 2.  tried on both mac and pc.  moddesc version 23 doesnt load.  21 does.

**Comment by Dzi4d3k** [comment]
@sootysax 
Why you are still using beta 2 when there is already final version of patch 1.3? With final version there is no problem with modDesc v23,

**Comment by Mogli12** [comment]
AutoTractor only works with FS15 patch 1.3 final or above. Most likely, it can work with patch 1.3 beta2. But it does not work with beta1 and there is not extra descVersion for the betas.
