### ISSUE TITLE
AutoTractor und Courseplay

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/AutoTractor#11]
hi mogli

ich nutze AutoTractor 2.0.9.4 und Courseplay 4.01.0109

sobald autoTractor im Modordner liegt und mein abfahrer eine entladestelle erreicht hat und das korn abgeladen hat , anschliessend will er wieder Gas geben und zurück aufs feld fahren , aber er kommt nicht mehr von der abladestelle weg ,,, alle räder am durch drehen (keine colli oder ähnliches im weg)

sobald autotractor aus dem modordner raus ist , funktioniert alles wie es soll , abfahrer dreht munter seine runden zwischen feld und abladestelle

keine log error was autotractor oder courseplay betrifft

grüsse grazy

**Comment by Mogli12** [comment]
Hi Grazy,

Ich habe absolut keine Idee, wie AutoTractor so ein Problem in Courseplay verursachen könnte. Gibt es auch ein Issue bei Courseplay?

Viele Grüße,
Mogli

**Comment by mngrazy** [comment]
bei courseplay was zu schreiben ist sinnlos ,,, die machen schon seit Juli nix mehr ^^
mit der offiziellen version von autoTractor von MH und der dev version von CP funzt alles

ein autoTractor archive von den ganzen dev versionen hast du nicht oder ? sodas man mal langsam rückwärts gehen könnte und testen ab wo der fehler auftritt ?!

grüsse grazy

**Comment by Mogli12** [comment]
Wenn es nur in einer aktuelle Version von AutoTractor passiert, dann muss ich es mir doch wohl mal anschauen. Da ich ja auch die fertige ZIP-Datei in Github einchecke, gibt es die komplette Historie seit dem 16 Juli, und zwar hier:
https://github.com/Mogli12/AutoTractor/commits/master/zzzAutoTractor.zip

Viele Grüße

**Comment by mngrazy** [comment]
so ich nochmal mogli :p 

also ich hab nun mal alle versionen von github getestet ,,,, hat mit keiner version funktioniert
der courseplay helfer bleibt nach dem entladen "stecken" alle räder am durch drehen
wie ich bereits geschrieben habe,,,wenn AutoTractor aus dem modsOrdner raus ist , funzt es alles 1a

aber ich habe nicht gleich aufgegeben ^^

wenn ich bei AutoTractor den Alternativen Helfer einstelle ,,, also nur umstell von Normalen Helfer auf Alternativen Helfer , dann fährt CP nach dem entladen weiter , lol , stell ich wieder auf normalen helfer im AT Hud , bleibt er wieder hängen 

sehr komisches ding :D 

aber vielleicht hilft dir dieser ansatz irgendwie ....

grüsse grazy

**Comment by Mogli12** [comment]
Hi,
Kannst Du mal schauen, ob Version 2.0.9.7 das Problem behebt? 
Vielen Dank!

**Comment by mngrazy** [comment]
Problem behoben !!!
funktioniert 1a wieder :)

danke dir mogli

**Comment by Mogli12** [comment]
Sehr schön!
