### ISSUE TITLE
Issue Vaederstad_SoilMod_Pack with AutoTractor v2.1 b9

### ISSUE THREAD

**Issue by Iscarriah** [Mogli12/AutoTractor#18]
Hi,

I have an issue with turn maneuver of the Vaederstad Rapid A600 Light.

With active side left, at the end of the lane it turns left then reverses to engage the next lane. I expected it to begin the turn maneuver by a turn to the right (the same way as the standard seeders and the Tempo F8 from the same pack).

**Comment by Mogli12** [comment]
Hi,

AutoTractor tries to find a track that suits all implements. But sprayer do not work very well together with SoilManagement. I saw the new Vaederstad bundle but did not yet have time to test.

Best regards

**Comment by Mogli12** [comment]
Hi,

I tested the RapidA 600S Light now. It should work with v2.1b10. I noticed that the sowing machine is also a cultivator. So you should turn on the "Frontpacker". This is the button in row 3 and column 5.

Best regards

**Comment by Iscarriah** [comment]
Hi and thanks for the update.

I tested v2.1b10 and the Rapid A600S Light turns as expected. But when I attach the Biospray Mini it turns again in the wrong direction. Same for the Tempo F8 : 
- seeder alone : OK
- with Düngertank Temp : wrong way

Seems the fertilizer tanks are causing the issue...

**Comment by Mogli12** [comment]
Hi,

This is strange. I tested it with the A600S Light and BioSpray Mini in Holzhausen. Did you turn on the "Frontpacker"? Can you paste two screen shots? One in the middle of the field and one at the beginning of the turn. Please show the AutoTractor HUD in both screen shots.

Thanks!

**Comment by Iscarriah** [comment]
Hello, retested again with some screenshots.

Standard map (Westbridge Hills) and tractor (Case Puma 160). Only Vaederstadt pack and AutoTractor in mod directory.
- Rapid A600S Light
  ![Rapid A600S Light 1](http://tof.canardpc.com/view/bd0a2701-90a6-41b0-b18c-eae0a5125c4c.jpg)
  ![Rapid A600S Light 2](http://tof.canardpc.com/view/1e1c1210-88a1-4c98-aa08-e768f9e69f68.jpg)
  Turning to the right. Active side changed at the beginning of the turning maneuver
- Rapid A600S Light with BioSpray mini
  ![Rapid A600S Light Bio 1](http://tof.canardpc.com/view/f586ad8d-cc7f-4d27-affe-14b6e23c23b0.jpg)
  ![Rapid A600S Light Bio 2](http://tof.canardpc.com/view/b03baadb-87c4-4c73-91ed-8a9b3dc8d86e.jpg)
  Turning to the left. Active side not changed
  ![Rapid A600S Light Bio 3](http://tof.canardpc.com/view/cc9e56d5-eceb-4cbb-8b86-48faf4a702b2.jpg)
  Active side changed when it begins reversing

Hope that helps !

**Comment by Mogli12** [comment]
Ah, ok and I see. But this is not a big problem right? AutoTractor can do this maneuver to both sides.

**Comment by Iscarriah** [comment]
Sure not a big issue, just the turning takes a more time that way. So the helper is less effective and I must fire him and drive myself ;-)

**Comment by Mogli12** [comment]
Hi, with 2.1 b11 it should not turn to the wrong side anymore. And I tried to improve the problem handling at the end of this turn sequence. If it does not find the correct way (title not green) it will go back until it finds it.

**Comment by Iscarriah** [comment]
Perfect ! It turns the correct side now and the the turning maneuver (especially the reversing) is also better. Great job, thanks !
