### ISSUE TITLE
Sanity check in draw function (AutoTractor.lua)

### ISSUE THREAD

**Issue by alfalfa6945** [Mogli12/AutoTractor#22]
Stefan;
 Just a heads up, but you may have a slight bug in the AutoTractor.lua, specifically in the draw function starting in line 298 "elseif self.acLAltPressed then". 
There appears to be no sanity check, so if you play the game without AutoCombine and push the lalt key, you will get errors in your log file. 

Thank you for all the work you've put into your scripts, it's hard to play the game without them.

**Comment by Mogli12** [comment]
Hi,
The two flags acLCtrlPressed and acLAltPressed have the same name in AutoTractor and AutoCombine. The values are set in function keyEvent.
Regards, Stefan

**Comment by alfalfa6945** [comment]
Thank you for that. Maybe this is just a typo?

g_currentMission:addHelpButtonText(AutoCombineHud.getText("AUTO_TRACTOR_UTURN_ON"), InputBinding.AUTO_TRACTOR_UTURN_ON_OFF)

"AutoCombineHud.getText" (lines 300-307)?
