### ISSUE TITLE
AutoTractor LS17

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/AutoTractor#31]
Hi! Hoffe das dieses super Tool auch in Ls 17 kommt! Deine Sachen sind wirklich super! Danke für deine tolle Arbeit!

**Comment by Mogli12** [comment]
Hi,

In LS15 gab es die Spezifikationen aiTractor und aiCombine. Beide wurden durch aiVehicle ersetzt. Diese beinhaltet nun nicht mehr die eigentlichen Fahrmanöver. Diese sind in verschiedene AIDriveStrategy... Klassen ausgelagert und gerade diese fehlen in der [ScriptDocu](https://gdn.giants-software.com/documentation_scripting.php).

=> Es wird wohl weder AutoTractor noch AutoCombine in FS17 geben. 

Ich werde mir selber den Kursgenerator in Courseplay genauer anschauen. Dort kann man sich ja schon in LS15 einen Kurs für ein Feld generieren lassen.

Viele Grüße
