### ISSUE TITLE
Functions disabled

### ISSUE THREAD

**Issue by sootysax** [Mogli12/AutoTractor#4]
Using the very latest dev version of AT.  Some of the functions are disabled when trying to use the Falcland Rotary Plow. (http://www.modhoster.com/mods/rotoaratro)

I cannot switch modes from circular mode to straight lines mode
I cannot change the active side from left to right
I cannot activate headland mode

**Comment by Mogli12** [comment]
Can you please send me a screen shot with AutoTractor HUD open?

**Comment by sootysax** [comment]
screen shot looks normal - nothing is greyed out actually, just nothing happens when you click on them. 

do u want a log?
